export enum BlocsEnum {
  BlockHero = "BlockHero",
  BlockReviews = "BlockReviews",
  BlockAboutCourse = "BlockAboutCourse",
  BlockAboutUs = "BlockAboutUs",
  BlockFormatLessons = "BlockFormatLessons",
  BlockAchivments = "BlockAchivments",
  BlockBenefits = "BlockBenefits",
  BlockServices = "BlockServices",
  BlockContactForm = "BlockContactForm",
  BlockTeamEducation = "BlockTeamEducation",
  BlockRequirement = "BlockRequirement",
  BlockContacts = "BlockContacts",
  BlockCourseForPeople = "BlockCourseForPeople",
  BlockCta = "BlockCta",
  BlockOurBenefits = "BlockOurBenefits",
  BlockStructEducation = "BlockStructEducation",
  BlockWhoTeach = "BlockWhoTeach",
  BlockSchedule = "BlockSchedule",
  BlockAbout = "BlockAbout",
  BlockReview = "BlockReview",
  BlockBlog = "BlockBlog",
  BlockContact = "BlockContact",
}
